"""add published_at to listings

Revision ID: 0084fa7610b3
Revises: 044ca705fe3c
Create Date: 2026-09-10 11:49:19.774388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0084fa7610b3'
down_revision: Union[str, Sequence[str], None] = '044ca705fe3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE listings SET published_at = created_at WHERE status = 'published'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'published_at')
    # ### end Alembic commands ###
