"""add password to sellers

Revision ID: 55d5038ad145
Revises: a4d9b2a0fbcb
Create Date: 2026-09-09 20:27:50.924957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d5038ad145'
down_revision: Union[str, Sequence[str], None] = 'a4d9b2a0fbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('sellers', sa.Column('password_hash', sa.String(), nullable=True))
    op.execute("UPDATE sellers SET password_hash = 'unusable' WHERE password_hash IS NULL")
    op.alter_column('sellers', 'password_hash', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'password_hash')
    # ### end Alembic commands ###
