"""add indexes on make and price

Revision ID: a4d9b2a0fbcb
Revises: 72e66c55beb0
Create Date: 2026-09-07 17:38:57.509846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d9b2a0fbcb'
down_revision: Union[str, Sequence[str], None] = '72e66c55beb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_listings_make'), 'listings', ['make'], unique=False)
    op.create_index(op.f('ix_listings_price'), 'listings', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_price'), table_name='listings')
    op.drop_index(op.f('ix_listings_make'), table_name='listings')
    # ### end Alembic commands ###
