import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex gap-4 p-4 border-b text-sm">
          <Link href="/listings" className="font-semibold">RightWhip</Link>
          <Link href="/listings">Browse</Link>
          <Link href="/map">Map</Link>
          <Link href="/favourites">Favourites</Link>
          <Link href="/saved-searches">Saved searches</Link>
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/login" className="ml-auto">Log in</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
